Repository areisle/quarantined_wizzards, pull requests merged in 2020-04, with the labels that each got.

#1 Create components
  .env.development
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo256.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.tsx
  src/Context/constants.ts
  src/Context/fixtures.ts
  src/Context/index.tsx
  src/Context/reducer.ts
  src/Context/utilities.ts
  src/Main.scss
  src/Main.tsx
  src/components/Avatar/index.scss
  src/components/Avatar/index.tsx
  src/components/BettingDialog/index.tsx
  src/components/ChooseTrumpDialog/index.scss
  src/components/ChooseTrumpDialog/index.tsx
  src/components/Footer/index.scss
  src/components/Footer/index.tsx
  src/components/GameBoard/index.scss
  src/components/GameBoard/index.tsx
  src/components/Header/index.scss
  src/components/Header/index.tsx
  src/components/JoinGameDialog/index.tsx
  src/components/PlayerDeck/index.scss
  src/components/PlayerDeck/index.tsx
  src/components/PlayingCard/index.scss
  src/components/PlayingCard/index.tsx
  src/components/Rules/index.tsx
  src/components/ScoreBoard/index.scss
  src/components/ScoreBoard/index.tsx
  src/components/StartGameDialog/index.tsx
  src/components/TrickWonDialog/index.tsx
  src/icons.tsx
  src/index.css
  src/logo.svg
  src/types.ts
Labels: enhancement

#2 Feature/socket server
  .gitignore
  config/jest.config.js
  package-lock.json
  package.json
  server/__tests__/index.test.js
  server/db/game.js
  server/db/index.js
  server/db/player.js
  server/db/round.js
  server/index.js
  server/main.js
Labels: enhancement

#24 Swap server to typescript
  .gitignore
  README.md
  config/jest.config.js
  package-lock.json
  package.json
  server/__tests__/index.test.ts
  server/db/game.ts
  server/db/index.ts
  server/db/player.ts
  server/db/round.ts
  server/index.ts
  server/main.js
  server/main.ts
  src/Context/index.tsx
  src/Context/reducer.ts
  src/Context/utilities.ts
  tsconfig.server.json
Labels: enhancement

#38 Feature/issue 31 wait after trick
  server/__tests__/index.test.ts
  server/db/index.ts
  server/db/round.ts
  server/index.ts
  src/types.ts
Labels: enhancement

#60 Bugfix/server set taken
  server/db/index.ts
  server/db/round.ts
Labels: bug

#61 feat: return trick winner with game state
  server/__tests__/index.test.ts
  server/db/index.ts
Labels: enhancement

#64 feat: trick started after trick complete should use next trick not current
  server/index.ts
Labels: bug

#63 feat: submit bet on press enter key
  src/components/BettingDialog/index.tsx
Labels: enhancement

#82 fix: do not check allowed card suit when lead is wizard
  server/db/round.ts
Labels: bug

#89 Bugfix/issue 72 sort cards
  server/__tests__/db.test.ts
  server/__tests__/index.test.ts
  server/db/index.ts
  server/db/round.ts
Labels: bug, enhancement

#91 fix: add card to trick before removing from hand
  server/db/round.ts
Labels: bug, server

#92 fix: send trump changed after round started
  server/index.ts
Labels: bug, server

#105 documentation: Add screen shots to the README
  README.md
  docs/choose-card.png
  docs/trick.png
Labels: documentation

#107 fix: emit game complete event on last round complete
  server/index.ts
  src/types.ts
Labels: bug, server

#114 fix: only remove first match
  server/__tests__/round.test.ts
  server/db/round.ts
Labels: bug

#116 feat: add join game option to start game dialog
  src/Context/index.tsx
  src/components/StartGameDialog/index.scss
  src/components/StartGameDialog/index.tsx
Labels: client, enhancement

#119 feat: add total rounds to round number in header
  src/Main.tsx
  src/components/Header/index.tsx
  src/types.ts
Labels: client, enhancement

#125 Bugfix/issue 123 no action
  server/db/round.ts
  src/Main.tsx
  src/components/Header/index.tsx
Labels: bug, server

#132 docs: add gameplay overview
  README.md
  docs/all-players-in.png
  docs/choose-card.png
  docs/motivation.png
  docs/place-bet.png
  docs/start-screen.png
Labels: documentation

#134 docs: add icon to readme
  README.md
Labels: documentation
